[package]
name = "enum-from-derive"
version = "0.1.0"
authors = ["Matt Williams <matwilliams@hotmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11.4"
quote = "0.3.12"

[dev-dependencies]
try_from = "0.2.1"
